const $ = s => document.querySelector(s);
const paths = {
 home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-3a8 6 0 0 1 16 0v3',wallet:'M3 6h17v15H3V6l14-3v3M16 12h5v5h-5z',flash:'m13 2-9 12h7l-1 8 10-13h-8z',snow:'M12 2v20M3 7l18 10M3 17 21 7M9 4l3 3 3-3M9 20l3-3 3 3',bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 21h4',calendar:'M4 5h16v16H4zM4 10h16M8 3v4M16 3v4M8 14h2M14 14h2M8 18h2',book:'M12 5v16M3 4c4-1 7 0 9 2 2-2 5-3 9-2v15c-4-1-7 0-9 2-2-2-5-3-9-2z',chart:'M4 3v18h17M8 16v-5M13 16V7M18 16v-9',check:'M7 3h10v3H7zM7 5H4v16h16V5h-3M8 13l3 3 5-6',door:'M5 21V3h14v18M2 21h20M14 12h1',group:'M9 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0M21 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0M1 21v-4a5 5 0 0 1 10 0v4M13 21v-4a5 5 0 0 1 10 0v4',chat:'M3 4h18v13H9l-6 4zM7 8h10M7 12h6',run:'M15 5a2 2 0 1 1 0-4 2 2 0 0 1 0 4M4 10l5-3 5 3 5 1M12 9l-3 6 5 3-1 4M9 15l-5 6',flask:'M9 2h6M10 2v7L3 20q-1 2 2 2h14q3 0 2-2L14 9V2M7 15h10',link:'m9 15 6-6M8 17l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0M16 7l2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0',map:'m3 5 6-2 6 2 6-2v17l-6 2-6-2-6 2zM9 3v17M15 5v17',help:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M9 8a3 3 0 1 1 4 3l-1 2M12 17h.01',headset:'M3 14v-3a9 9 0 0 1 18 0v3M3 12h4v7H3zM17 12h4v7h-4zM21 19q0 3-7 3',settings:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',gift:'M3 8h18v5H3zM5 13v8h14v-8M12 8v13M12 8C1 8 6-2 12 8c6-10 11 0 0 0',shield:'m12 2 9 4v7q-2 7-9 9-7-2-9-9V6zM8 12l3 3 5-6',refresh:'M20 8a8 8 0 1 0 0 8M20 3v5h-5',spark:'m12 2 2 7 7 3-7 2-2 8-2-8-7-2 7-3z'};
const icon = key => `<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[key] || paths.book}"/></svg>`;
const student = [['绩点计算','chart','gpa-calculator'],['学业情况查询','check','academic-progress'],['考试安排','calendar','exam'],['空教室查询','door','classroom'],['班级课表','group','class-schedule'],['教材查询','book','textbooks'],['财务查询','wallet','finance'],['宿舍电费查询','flash','electricity'],['帕鲁点评','chat','review'],['体测计算器','run','fitness-test'],['实验','flask','experiments']];
const teacher = [['学生成绩查询','check','teacher-grade-query'],['成绩分析','chart','teacher-grade-stats'],['我的权限','shield','teacher-permissions'],['我的排班','calendar','teacher-duty-schedule'],['监考安排','book','teacher-exam']];
const services = [['绑定/解绑校园账号','link','campus-bind'],['校历','calendar','calendar'],['校园地图','map','map'],['常见问题及解答','help','faq'],['加入用户群','group','group'],['联系客服','headset','contact'],['设置','settings','settings']];
const routes = [...student,...teacher,...services,['管理后台','shield','console-panel'],['积分商城','gift','points-mall'],['通知','bell','announcement'],['管理我的鼓励语','spark','encouragement'],['完整课表','calendar','schedule']];
let role='student',scenario='normal',quote='慢慢来，你正在成为想成为的自己。',networkOpen=true,avatar='',timer;
const shortcuts = {student:['gpa-calculator','electricity'],admin:['gpa-calculator','electricity'],teacher:['teacher-grade-query','teacher-exam'],freshman:[],guest:[]};
const isStudent = () => role==='student'||role==='admin';
const authenticated = () => role!=='guest';
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),2300)}
function modal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function entry(item){return `<button class="feature" data-action="${item[2]}"><span class="iconbox">${icon(item[1])}</span><span>${item[0]}</span></button>`}
function service(item){return `<button class="service" data-action="${item[2]}">${icon(item[1])}<span>${item[0]}</span><span class="chevron">›</span></button>`}
function render(){
 const fresh=role==='freshman',guest=role==='guest',empty=scenario==='empty';
 $('#home').innerHTML=`<div class="topline">${!fresh?`<button class="resource-trigger" data-action="resources" aria-label="查看校园卡、照明和空调余额"><span class="light ${guest?'neutral':''}">${icon('wallet')}</span><span class="light ${guest||scenario==='unbound'?'neutral':'warn'}">${icon('flash')}</span><span class="light ${guest||scenario==='unbound'?'neutral':'danger'}">${icon('snow')}</span></button>`:`<span class="eyebrow">你好，新同学</span>`}<button class="notice" data-action="announcement">${icon('bell')}通知 <span class="badge">2</span></button></div><div class="greeting"><span class="date">09 / 09 · 星期三</span><h2>上午好，乘风人<span style="color:var(--blue)">！</span></h2></div><button class="quote" data-action="encouragement" aria-label="管理我的鼓励语"><span id="quote-text"></span><span>↗</span></button>${scenario==='expired'?'<button class="alert" data-action="campus-bind">登录已过期 · 当前为缓存数据，点击重新登录 ›</button>':''}${fresh?`<section class="card"><div class="section-head"><h3>待办事项</h3><span class="week">迎新季</span></div><button class="todo" data-action="map"><span class="iconbox">${icon('map')}</span><span><b>校园地图</b><small>南苑 / 北苑 · 查看迎新常用地图</small></span><span>›</span></button>${empty?'<div class="empty">暂无待办事项，请留意后续通知～</div>':'<button class="todo" data-action="todo"><span class="iconbox">'+icon('check')+'</span><span><b>查看入学报到指引</b><small>迎新待办示例 · 截止 09 月 12 日</small></span><span>›</span></button>'}</section>`:`<section class="card"><div class="section-head"><h3>今日课程 <button class="week" data-action="calendar">第 2 周</button></h3><button class="link" data-action="schedule">完整课表 ↗</button></div><div class="weekstrip">${['一','二','三','四','五','六','日'].map((d,i)=>`<div class="day ${i===2?'today':''}">${d}<b>${7+i}</b></div>`).join('')}</div>${empty||guest?`<div class="empty">${guest?'绑定校园账号，查看你的课程':'今天没有课哦，留一点时间给自己。'}</div>${guest?'<button class="primary" data-action="campus-bind">绑定校园账号</button>':''}`:`<div class="courses"><div class="course"><div class="time">08:00<br><small>09:35</small></div><div class="course-body"><strong>大学物理 A</strong><p>第 1–2 节 · 北教 302</p></div></div><div class="course"><div class="time">10:00<br><small>11:35</small></div><div class="course-body active"><span class="tag">即将开始</span><strong>模拟电子技术</strong><p>第 3–4 节 · 南教 205</p></div></div><div class="course"><div class="time">14:00<br><small>15:35</small></div><div class="course-body"><strong>概率论与数理统计</strong><p>第 5–6 节 · 北教 401</p></div></div></div>`}</section><section class="card"><div class="section-head"><h3>考试安排</h3><button class="link" data-action="exam">全部考试 ↗</button></div>${empty||guest?'<div class="empty">本学期暂无考试安排</div>':'<div class="exam-card"><div class="exam-line"><strong>大学英语（补考）</strong><span class="pill">未开始 · 3 天后</span></div><div class="exam-meta"><span>日期 <b>09 月 12 日</b></span><span>时间 <b>09:00–11:00</b></span><span>地点 <b>南教 106</b></span><span>座位 <b>025</b></span></div></div>'}</section>`}<div class="gentle">${icon('spark')}把今天过好，就是很了不起的事。</div>`;
 $('#quote-text').textContent=quote;
 const features=isStudent()?student:role==='teacher'?teacher:[student[9]];
 const list=[...(role==='admin'?[['管理后台','shield','console-panel']]:[]),...(!fresh&&!guest?[['积分商城','gift','points-mall']]:[]),...services];
 $('#profile').innerHTML=`${guest?'<section class="identity"><h2>你好，乘风人</h2><p>绑定校园账号，开启你的校园日常。</p><button class="primary" data-action="campus-bind">请先绑定校园账号 →</button></section>':`<section class="identity" id="identity"><button class="identity-info" data-action="identity" aria-label="查看用户身份标识">ⓘ</button><div class="identity-top"><button class="avatar" data-action="avatar" aria-label="更换头像">${avatar?'<img src="'+avatar+'" alt="头像">':icon('user')}</button><div><h2>${role==='teacher'?'乘风老师':'乘风同学'}</h2><small>${fresh?'身份：新生':role==='teacher'?'工号：DEMO-026 · 身份：教师':'学号：DEMO-2026 · 身份：学生'}</small></div></div><div class="identity-meta"><span>电子信息与自动化学院</span>${role!=='teacher'?'<span>· '+(fresh?'2026 级新生':'电子信息 2301 班')+'</span>':''}</div>${!fresh?'<div class="membership"><b>✦ 帕鲁 Premium</b><span>到期：2027.09.01</span></div>':''}</section>`}${!fresh&&!guest?`<section class="card network"><div class="section-head"><button class="network-head" data-action="network">${icon('flash')}<h3>校园网信息</h3></button><div class="network-actions"><button data-action="network-refresh" aria-label="刷新校园网信息">${icon('refresh')}</button><button data-action="network" aria-label="展开或收起校园网信息" aria-expanded="${networkOpen}">${networkOpen?'⌃':'⌄'}</button></div></div>${networkOpen?'<div class="network-body"><div class="network-stats"><div><strong>28.6<small>已用 / GB</small></strong></div><div><strong>71.4<small>可用 / GB</small></strong></div><div><strong>25.00<small>余额 / 元</small></strong></div><div><strong class="status-ok">● 正常</strong><small>账户状态</small></div></div><div class="meter"><i></i></div><div class="network-details"><span>套餐类型：校园畅享 100G</span><span>计费方式：包月</span><span>计费周期：09.01–09.30</span><span>到期日期：2026.09.30</span></div></div>':''}</section>`:''}<section class="card"><div class="section-head"><h3>${role==='teacher'?'教学服务':fresh||guest?'校园工具':'校园服务'}</h3><span class="date">${features.length} 项</span></div><div class="features">${features.map(entry).join('')}</div></section><section class="card service-list">${list.map(service).join('')}</section><footer class="foot">Version 3.3.0 · “Yoisaki Kanade” / 2026.9.6 更新<br>凌音网络工作室 × 中国民航大学<br>电子信息与自动化学院 联合出品<br>Copyright © 2024–2026 Lingworks. All Rights Reserved.<br>凌音网络工作室 版权所有</footer>`;
 document.querySelectorAll('.tabbar').forEach((nav,i)=>nav.innerHTML=`<button class="${i===0?'selected':''}" data-tab="home">${icon('home')}<span>首页</span></button>${shortcuts[role].map(id=>{const item=routes.find(x=>x[2]===id);return `<button data-action="${id}">${icon(item[1])}<span>${item[0]}</span></button>`}).join('')}<button class="${i===1?'selected':''}" data-tab="profile">${icon('user')}<span>个人中心</span></button>`);
 const identity=$('#identity');if(identity){let hold;identity.addEventListener('pointerdown',e=>{if(!e.target.closest('button'))hold=setTimeout(()=>action('identity'),650)});['pointerup','pointercancel','pointerleave'].forEach(name=>identity.addEventListener(name,()=>clearTimeout(hold)))}
}
function resources(){
 if(!authenticated())return action('campus-bind');
 const bound=scenario!=='unbound';
 modal('校园账户状态',`<p>上次查询：今天 09:41 · 示例数据</p><div class="resource-row"><span>校园卡余额<small>● 余额充足</small></span><span><b>86.50</b> 元</span></div><div class="resource-row"><span>照明余额<small>${bound?'● 余额偏低 · 免费 5.00 + 收费 7.80':'未绑定宿舍'}</small></span><span><b>${bound?'12.80':'—'}</b> 度</span></div><div class="resource-row"><span>空调余额<small>${bound?'● 余额不足 · 免费 0.00 + 收费 3.20':'未绑定宿舍'}</small></span><span><b>${bound?'3.20':'—'}</b> 度</span></div>${!bound?'<p>未绑定宿舍，本次只查询校园卡余额。</p>':''}<button class="primary" data-action="resource-refresh">重新查询</button>`)
}
function action(id){
 if(id==='resources')return resources();
 if(id==='resource-refresh'){const b=$('[data-action="resource-refresh"]');b.disabled=true;b.textContent='正在查询…';return setTimeout(()=>{if($('#modal').open&&$('#modal-title').textContent==='校园账户状态')resources();toast('示例账户状态已刷新')},650)}
 if(id==='network'){networkOpen=!networkOpen;return render()}
 if(id==='network-refresh')return modal('需要输入验证码','<p>校园网刷新验证演示，请输入下方 4 位验证码。</p><div class="route" style="font-size:27px;letter-spacing:12px;text-align:center">P4LU</div><p><input id="captcha" type="text" maxlength="4" placeholder="请输入 4 位验证码" aria-label="验证码"></p><button class="primary" data-action="captcha-submit" disabled>确认</button>');
 if(id==='captcha-submit'){if($('#captcha').value.toUpperCase()!=='P4LU')return toast('验证码不正确，请重新输入');$('#modal').close();networkOpen=true;render();return toast('校园网示例信息已刷新')}
 if(id==='avatar')return $('#avatar-file').click();
 if(id==='identity')return modal('用户身份标识','<p>OpenID：DEMO-OPENID<br>自定义 ID：DEMO-CUSTOM-ID</p><p>此处为虚构标识；保留原页面长按信息卡片的入口。</p><button class="primary" data-action="copy-id">复制全部</button>');
 if(id==='copy-id'){return navigator.clipboard?.writeText('OpenID: DEMO-OPENID\nCustom ID: DEMO-CUSTOM-ID').then(()=>toast('已复制示例标识')).catch(()=>toast('浏览器不允许复制，请手动选取文字'))||toast('请手动选取文字复制')}
 if(id==='encouragement'){modal('管理我的鼓励语','<p>给今天的自己留一句话。</p><textarea id="quote-input" aria-label="鼓励语" maxlength="60"></textarea><button class="primary" data-action="save-quote">保存鼓励语</button>');$('#quote-input').value=quote;return}
 if(id==='save-quote'){const value=$('#quote-input').value.trim();if(!value)return toast('请写下一句鼓励语');quote=value;render();$('#modal').close();return toast('鼓励语已更新')}
 if(id==='settings')return modal('设置',`<button class="service" data-action="appearance">${icon('settings')}外观 · ${document.body.classList.contains('dark')?'深色':'浅色'}<span class="chevron">切换 ›</span></button>${!['guest','freshman'].includes(role)?'<button class="service" data-action="shortcuts">'+icon('check')+'底栏快捷入口<span class="chevron">自定义 ›</span></button>':''}<p>本次演示提供外观与底栏快捷入口调整。正式版设置页保持原功能。</p><code class="route">/pages/settings/settings</code>`);
 if(id==='appearance'){document.body.classList.toggle('dark');return action('settings')}
 if(id==='shortcuts'){const options=isStudent()?student:teacher.filter(x=>['teacher-grade-query','teacher-grade-stats','teacher-exam'].includes(x[2]));return modal('底栏快捷入口',`<p>最多选择 2 项，首页与个人中心始终保留。</p>${options.map(x=>`<label class="choice"><input type="checkbox" name="shortcut" value="${x[2]}" ${shortcuts[role].includes(x[2])?'checked':''}>${x[0]}</label>`).join('')}<button class="primary" data-action="save-shortcuts">保存</button>`)}
 if(id==='save-shortcuts'){const checked=[...document.querySelectorAll('[name="shortcut"]:checked')].map(x=>x.value);if(checked.length>2)return toast('最多选择 2 个快捷入口');shortcuts[role]=checked;render();$('#modal').close();return toast('底栏快捷入口已更新')}
 if(id==='map')return modal('校园地图','<p>请选择校区。正式版打开相应校园地图。</p><button class="service" data-action="map-south">南苑地图<span class="chevron">›</span></button><button class="service" data-action="map-north">北苑地图<span class="chevron">›</span></button>');
 if(id.startsWith('map-'))return modal(id==='map-south'?'南苑地图':'北苑地图','<p>已保留对应校区的地图入口。本原型不加载真实地图，避免将示意图误作导航依据。</p>');
 if(id==='group')return modal('加入用户群','<p>正式版在此展示用户群二维码，支持扫码加入用户群。</p><div class="empty">用户群二维码展示区<br><small>设计演示不放置可扫码的真实群码</small></div><p>若二维码过期请联系客服。</p><button class="primary" data-action="contact">联系客服</button>');
 if(id==='contact')return modal('联系客服','<p>此入口在小程序中打开微信客服会话。HTML 演示不发送消息。</p>');
 if(id==='schedule')return modal('完整课表',`<p>第 2 周 · 周一至周日完整呈现 · 示例课表</p><table class="schedule-grid"><thead><tr><th>节次</th>${['一','二','三','四','五','六','日'].map(d=>'<th>'+d+'</th>').join('')}</tr></thead><tbody>${['1–2','3–4','5–6','7–8'].map((t,i)=>`<tr><th>${t}</th>${Array.from({length:7},(_,d)=>`<td class="${d===2&&i<3?'busy':''}">${d===2&&i<3?['大学物理','模拟电子','概率论'][i]:'—'}</td>`).join('')}</tr>`).join('')}</tbody></table><p>正式版保留完整周课表及其操作。</p><code class="route">/pages/schedule/schedule</code>`);
 if(id==='announcement')return modal('通知','<div class="resource-row"><span><b style="font:600 14px var(--body)">欢迎回到校园</b><small>09 月 09 日 · 示例通知</small></span><span class="badge">新</span></div><p>公告列表及公告详情入口保留，正式版沿用原通知服务。</p><code class="route">/pages/announcement/announcement</code>');
 if(id==='todo')return modal('入学报到指引','<p>新生待办示例，正式版保留待办标题、标签、说明、截止时间及配置链接跳转。</p>');
 const item=routes.find(x=>x[2]===id);if(item)modal(item[0],`<p>“${item[0]}”入口已保留。正式接入时打开现有功能页面，继续沿用原有身份验证和业务流程。</p><code class="route">/pages/${id}/${id}</code><p>当前为界面演示，不查询或修改真实账号数据。</p>`);
}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){document.body.classList.toggle('profile-active',tab.dataset.tab==='profile');if(innerWidth>650)$(tab.dataset.tab==='profile'?'.profile-screen':'.home-screen').scrollIntoView({block:'nearest'});return}const button=e.target.closest('[data-action]');if(button)action(button.dataset.action)});
document.addEventListener('input',e=>{if(e.target.id==='captcha')$('[data-action="captcha-submit"]').disabled=e.target.value.length!==4});
$('#close').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#role').onchange=e=>{role=e.target.value;render()};$('#scenario').onchange=e=>{scenario=e.target.value;render()};$('#theme').onclick=()=>document.body.classList.toggle('dark');
$('#avatar-file').onchange=e=>{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return toast('请选择图片文件');if(avatar)URL.revokeObjectURL(avatar);avatar=URL.createObjectURL(file);render();toast('演示头像已更换')};
render();
